### ISSUE TITLE
Typekit (webfont) doesn't work

### ISSUE THREAD

**Issue by marckohlbrugge** [DeviaVir/pixelratio-screenshots#1]
Thanks for creating this!

I ran into an issue with websites using [Typekit](https://typekit.com) where text either doesn't show up at all, or doesn't use the custom web font. I tried some other PhantomJS scripts as wel which do seem to work fine.

Here's an example (with image attached):

``` bash
pixelratio-screenshots master % phantomjs pixelratio.js http://typekit.com typekit.png 2
Temporarily blocking too soon request to  https://typekit.com/assets/home-2b8fe1072eceedc70732bb196ac6bb9a.js
Temporarily blocking too soon request to  https://wwwimages2.adobe.com/assets/globalnav/v1.1.4/js/globalnav.js
Temporarily blocking too soon request to  https://static.adobelogin.com/imslib/imslib.min.js?client_id=TypeKit2
Temporarily blocking too soon request to  https://use.typekit.net/uxm4kvz.js
Temporarily blocking too soon request to  https://ssl.google-analytics.com/ga.js
ReferenceError: Can't find variable: Typekit

  https://typekit.com/:819
ReferenceError: Can't find variable: tk

  https://typekit.com/:833
Temporarily blocking too soon request to  https://js-agent.newrelic.com/nr-768.min.js
Setting window.devicePixelRatio to 2
```

In this particular case it actually throws out a Javascript error. In other test it doesn't, but renders the text with fallback fonts.

![typekit](https://cloud.githubusercontent.com/assets/93276/12536679/510d42d6-c2ac-11e5-92a0-f70adff123ef.jpg)

**Comment by DeviaVir** [comment]
@marckohlbrugge thanks for reporting this! I was playing around with it and it turns out there seems to be no way to kill their JS and then add it back later without completely destroying the layout.

I have been hacking on a `pixelratio.js` which has support for these typescripty things, I'm not sure yet if I want to have this in master, but it might help you forward:
https://gist.github.com/DeviaVir/fba6aec84786f0f074f3

result:
https://s3.amazonaws.com/f.cl.ly/items/3O0F3O3Z402d1I0Y2T1h/typekit.png

**Comment by DeviaVir** [comment]
Looked like the solution in #2 also worked for other sites, so merging. Let me know if you run into anything else!

**Comment by marckohlbrugge** [comment]
Just cloned `master`, but it's still not rendering the text for me on the Typekit site. Did it work for you?

**Comment by DeviaVir** [comment]
@marckohlbrugge sorry I didn't notice your comment earlier, it did work for me as the screenshot in my previous comment shows:
https://s3.amazonaws.com/f.cl.ly/items/3O0F3O3Z402d1I0Y2T1h/typekit.png
